-- V4: 用户表增加安全相关字段
ALTER TABLE TM_USER
    ADD COLUMN LAST_LOGIN_TIME DATETIME AFTER STATUS;
ALTER TABLE TM_USER
    ADD COLUMN LOGIN_FAIL_COUNT INT DEFAULT 0 AFTER LAST_LOGIN_TIME;
ALTER TABLE TM_USER
    ADD COLUMN LOCK_UNTIL DATETIME AFTER LOGIN_FAIL_COUNT;

-- 更新 admin 密码为 BCrypt 加密的 admin2026
-- 此 hash 由 BCrypt.hashpw("admin2026") 生成
UPDATE TM_USER
SET PASSWORD_HASH = '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
WHERE USERNAME = 'admin';

-- AnalysisTask 扩展字段：通知渠道和推送对象
ALTER TABLE TM_ANALYSIS_TASK
    ADD COLUMN NOTIFICATION_CHANNELS VARCHAR(500) AFTER DESCRIPTION;
ALTER TABLE TM_ANALYSIS_TASK
    ADD COLUMN NOTIFICATION_TARGETS VARCHAR(500) AFTER NOTIFICATION_CHANNELS;
