-- V5: 持仓表增加定投字段
ALTER TABLE TM_FUND_PORTFOLIO
    ADD COLUMN AUTO_DIP TINYINT(1) DEFAULT 0 COMMENT '是否开启定投',
    ADD COLUMN DIP_AMOUNT DECIMAL(12,2) DEFAULT NULL COMMENT '定投金额(元)',
    ADD COLUMN DIP_FREQUENCY VARCHAR(20) DEFAULT 'MONTHLY' COMMENT '定投频率: WEEKLY/BIWEEKLY/MONTHLY';
