-- ============================================================
-- schema.sql
-- Fund Analysis Agents - Full DDL (merged from V1/V3/V4/V5)
-- MySQL 8.0+
-- ============================================================

-- 1. User
CREATE TABLE IF NOT EXISTS TM_USER
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME         VARCHAR(50) NOT NULL,
    NICKNAME         VARCHAR(50),
    EMAIL            VARCHAR(100),
    PHONE            VARCHAR(20),
    PASSWORD_HASH    VARCHAR(255),
    ROLE             VARCHAR(20) NOT NULL DEFAULT 'USER',
    STATUS           TINYINT     NOT NULL DEFAULT 1,
    LAST_LOGIN_TIME  DATETIME,
    LOGIN_FAIL_COUNT INT                  DEFAULT 0,
    LOCK_UNTIL       DATETIME,
    CREATED_AT       DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_USER_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User account';

-- 2. User Profile
CREATE TABLE IF NOT EXISTS TM_USER_PROFILE
(
    ID                       BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID                  BIGINT        NOT NULL,
    RISK_LEVEL               VARCHAR(20)   NOT NULL DEFAULT 'BALANCED',
    INVESTMENT_HORIZON       VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM',
    MAX_DRAWDOWN_TOLERANCE   DECIMAL(5, 2) NOT NULL DEFAULT 20.00,
    PREFERRED_INDUSTRIES     JSON,
    AVOIDED_INDUSTRIES       JSON,
    FUND_SCALE_PREFERENCE    VARCHAR(20)   NOT NULL DEFAULT 'ANY',
    TURNOVER_TOLERANCE       VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM',
    ACCEPT_NEW_FUND          TINYINT       NOT NULL DEFAULT 0,
    CONCENTRATION_PREFERENCE VARCHAR(20)   NOT NULL DEFAULT 'ANY',
    COMPLETED                TINYINT       NOT NULL DEFAULT 0,
    CREATED_AT               DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT               DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_PROFILE_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User investment profile';

-- 3. Fund Info
CREATE TABLE IF NOT EXISTS TM_FUND_INFO
(
    ID                 BIGINT PRIMARY KEY AUTO_INCREMENT,
    FUND_CODE          VARCHAR(10) NOT NULL,
    FUND_NAME          VARCHAR(100),
    FUND_TYPE          VARCHAR(30),
    MANAGEMENT_COMPANY VARCHAR(100),
    FUND_MANAGER       VARCHAR(50),
    ESTABLISH_DATE     DATE,
    FUND_SCALE         DECIMAL(18, 4),
    NAV                DECIMAL(10, 4),
    ACCUMULATED_NAV    DECIMAL(10, 4),
    DAY_GROWTH_RATE    DECIMAL(8, 4),
    SHARPE_RATIO       DECIMAL(8, 4),
    MAX_DRAWDOWN       DECIMAL(8, 4),
    VOLATILITY         DECIMAL(8, 4),
    DATA_UPDATE_TIME   DATETIME,
    CREATED_AT         DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT         DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_FUND_CODE (FUND_CODE),
    INDEX              IDX_FUND_TYPE (FUND_TYPE),
    INDEX              IDX_FUND_NAME (FUND_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund basic information';

-- 4. Fund Portfolio (includes V5 DIP fields)
CREATE TABLE IF NOT EXISTS TM_FUND_PORTFOLIO
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID        BIGINT      NOT NULL,
    FUND_CODE      VARCHAR(10) NOT NULL,
    HOLDING_AMOUNT DECIMAL(18, 4),
    AVG_COST       DECIMAL(10, 4),
    PURCHASE_DATE  DATETIME,
    NOTES          VARCHAR(500),
    AUTO_DIP       TINYINT(1)     DEFAULT 0 COMMENT '是否开启定投',
    DIP_AMOUNT     DECIMAL(12, 2)       DEFAULT NULL COMMENT '定投金额',
    DIP_FREQUENCY  VARCHAR(20)          DEFAULT 'MONTHLY' COMMENT '定投频率',
    CREATED_AT     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_PORTFOLIO_USER_FUND (USER_ID, FUND_CODE),
    INDEX          IDX_PORTFOLIO_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User fund portfolio';

-- 5. Watch List
CREATE TABLE IF NOT EXISTS TM_WATCH_LIST
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID    BIGINT      NOT NULL,
    FUND_CODE  VARCHAR(10) NOT NULL,
    PRIORITY   INT         NOT NULL DEFAULT 0,
    NOTES      VARCHAR(500),
    CREATED_AT DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_WATCH_USER_FUND (USER_ID, FUND_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User watch list';

-- 6. Analysis Task (includes V4 notification fields)
CREATE TABLE IF NOT EXISTS TM_ANALYSIS_TASK
(
    ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID               BIGINT      NOT NULL,
    FUND_CODE             VARCHAR(10),
    TASK_TYPE             VARCHAR(30) NOT NULL,
    REPORT_TYPE           VARCHAR(30),
    CRON_EXPRESSION       VARCHAR(50),
    ENABLED               TINYINT     NOT NULL DEFAULT 1,
    DESCRIPTION           VARCHAR(255),
    NOTIFICATION_CHANNELS VARCHAR(500),
    NOTIFICATION_TARGETS  VARCHAR(500),
    TIMEOUT_MINUTES       INT                  DEFAULT 30 COMMENT '任务超时时间(分钟)',
    CREATED_AT            DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX                 IDX_TASK_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Analysis task definition';

-- 7. Task Execution
CREATE TABLE IF NOT EXISTS TM_TASK_EXECUTION
(
    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    TASK_ID           BIGINT,
    FUND_CODE         VARCHAR(10),
    FUND_NAME         VARCHAR(100),
    BATCH_NO          VARCHAR(50) NOT NULL,
    STATUS            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PROGRESS          INT                  DEFAULT 0,
    CURRENT_STAGE     VARCHAR(100),
    TRIGGER_TYPE      VARCHAR(20)          DEFAULT 'MANUAL',
    SCHEDULED_TIME    DATETIME,
    START_TIME        DATETIME,
    END_TIME          DATETIME,
    INPUT_SNAPSHOT_ID VARCHAR(100),
    ERROR_MESSAGE     TEXT,
    RETRY_COUNT       INT         NOT NULL DEFAULT 0,
    MAX_RETRY         INT         NOT NULL DEFAULT 3,
    CREATED_AT        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_EXECUTION_BATCH (BATCH_NO),
    INDEX             IDX_EXECUTION_TASK (TASK_ID),
    INDEX             IDX_EXECUTION_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Task execution record';

-- 8. Analysis Report
CREATE TABLE IF NOT EXISTS TM_ANALYSIS_REPORT
(
    ID                        BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID                   BIGINT   NOT NULL,
    EXECUTION_ID              BIGINT,
    BATCH_NO                  VARCHAR(50),
    REPORT_VERSION            INT      NOT NULL DEFAULT 1,
    INPUT_SNAPSHOT_ID         VARCHAR(100),
    FUND_CODE                 VARCHAR(10),
    REPORT_TYPE               VARCHAR(30),
    REPORT_DATE               DATE,
    OVERALL_RATING            VARCHAR(10),
    OVERALL_SCORE             DECIMAL(5, 2),
    CONFIDENCE_LEVEL          VARCHAR(20),
    RECOMMENDATION            VARCHAR(20),
    POSITION_SUGGESTION       DECIMAL(5, 2),
    TIME_HORIZON              VARCHAR(20),
    ADD_POSITION_TRIGGER      VARCHAR(500),
    REDUCE_POSITION_TRIGGER   VARCHAR(500),
    INVALIDATION_CONDITION    VARCHAR(500),
    FUND_ANALYST_RESULT       JSON,
    TECHNICAL_ANALYST_RESULT  JSON,
    INDUSTRY_ANALYST_RESULT   JSON,
    SENTIMENT_ANALYST_RESULT  JSON,
    NEWS_ANALYST_RESULT       JSON,
    MANAGER_ANALYST_RESULT    JSON,
    BULLISH_RESEARCHER_RESULT JSON,
    BEARISH_RESEARCHER_RESULT JSON,
    DEBATE_SUMMARY            JSON,
    TRADER_RESULT             JSON,
    RISK_MANAGER_RESULT       JSON,
    PORTFOLIO_ADVISOR_RESULT  JSON,
    SUMMARY                   TEXT,
    HTML_CONTENT              LONGTEXT,
    CREATED_AT                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX                     IDX_REPORT_USER_FUND (USER_ID, FUND_CODE),
    INDEX                     IDX_REPORT_DATE (REPORT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Analysis report';

-- 9. AI Provider Config (includes V3 PROVIDER_TYPE field)
CREATE TABLE IF NOT EXISTS TM_AI_PROVIDER_CONFIG
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROVIDER_CODE       VARCHAR(30) NOT NULL,
    PROVIDER_NAME       VARCHAR(50),
    PROVIDER_TYPE       VARCHAR(20) NOT NULL DEFAULT 'openai',
    API_KEY_ENCRYPTED   TEXT,
    BASE_URL            VARCHAR(255),
    ENABLED             TINYINT     NOT NULL DEFAULT 1,
    CONNECTIVITY_STATUS VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    LAST_CHECK_TIME     DATETIME,
    CREATED_AT          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_PROVIDER_CODE (PROVIDER_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI provider configuration';

-- 10. Agent Model Binding
CREATE TABLE IF NOT EXISTS TM_AGENT_MODEL_BINDING
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    AGENT_ID      VARCHAR(50) NOT NULL,
    THINK_LEVEL   VARCHAR(20) NOT NULL,
    PROVIDER_CODE VARCHAR(30) NOT NULL,
    MODEL_ID      VARCHAR(50) NOT NULL,
    ENABLED       TINYINT     NOT NULL DEFAULT 1,
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_AGENT_THINK (AGENT_ID, THINK_LEVEL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent to model binding';

-- 11. Notification Channel
CREATE TABLE IF NOT EXISTS TM_NOTIFICATION_CHANNEL
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID      BIGINT      NOT NULL,
    CHANNEL_TYPE VARCHAR(20) NOT NULL,
    CONFIG_JSON  JSON,
    ENABLED      TINYINT     NOT NULL DEFAULT 1,
    CREATED_AT   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_CHANNEL_USER_TYPE (USER_ID, CHANNEL_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Notification channel config';

-- 12. Datasource Config
CREATE TABLE IF NOT EXISTS TM_DATASOURCE_CONFIG
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    SOURCE_CODE         VARCHAR(30) NOT NULL,
    SOURCE_NAME         VARCHAR(50),
    SOURCE_TYPE         VARCHAR(20),
    BASE_URL            VARCHAR(255),
    API_KEY_ENCRYPTED   TEXT,
    DATA_LEVEL          VARCHAR(5)  NOT NULL DEFAULT 'L2',
    ENABLED             TINYINT     NOT NULL DEFAULT 1,
    PRIORITY            INT         NOT NULL DEFAULT 10,
    CONNECTIVITY_STATUS VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    LAST_CHECK_TIME     DATETIME,
    CREATED_AT          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_SOURCE_CODE (SOURCE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='External datasource config';

-- 13. System Config
CREATE TABLE IF NOT EXISTS TM_SYSTEM_CONFIG
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONFIG_GROUP VARCHAR(50)  NOT NULL,
    CONFIG_KEY   VARCHAR(100) NOT NULL,
    CONFIG_VALUE TEXT,
    CONFIG_TYPE  VARCHAR(20)  NOT NULL DEFAULT 'STRING',
    DESCRIPTION  VARCHAR(255),
    CREATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_CONFIG_GROUP_KEY (CONFIG_GROUP, CONFIG_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System configuration';

-- 14. Notification
CREATE TABLE IF NOT EXISTS TM_NOTIFICATION
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID       BIGINT      NOT NULL,
    REPORT_ID     BIGINT,
    CHANNEL       VARCHAR(20),
    TITLE         VARCHAR(200),
    CONTENT       TEXT,
    STATUS        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SENT_TIME     DATETIME,
    ERROR_MESSAGE VARCHAR(500),
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX         IDX_NOTIFICATION_USER_STATUS (USER_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Notification record';

-- 15. Fund Recommendation
CREATE TABLE IF NOT EXISTS TM_FUND_RECOMMENDATION
(
    ID                     BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID                BIGINT   NOT NULL,
    BATCH_NO               VARCHAR(50),
    MARKET_TEMPERATURE     VARCHAR(20),
    MARKET_SCORE           INT,
    MARKET_ANALYSIS        JSON,
    RECOMMENDED_FUNDS      JSON,
    PORTFOLIO_CHECK_RESULT JSON,
    REPORT_CONTENT         TEXT,
    CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX                  IDX_RECOMMEND_USER (USER_ID),
    INDEX                  IDX_RECOMMEND_BATCH (BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund recommendation';

-- 16. Data Snapshot
CREATE TABLE IF NOT EXISTS TM_DATA_SNAPSHOT
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    SNAPSHOT_ID   VARCHAR(50) NOT NULL,
    SNAPSHOT_TYPE VARCHAR(30) NOT NULL,
    SNAPSHOT_DATE DATE,
    DATA_CONTENT  JSON,
    SOURCE        VARCHAR(30),
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_SNAPSHOT_ID (SNAPSHOT_ID),
    INDEX         IDX_SNAPSHOT_TYPE_DATE (SNAPSHOT_TYPE, SNAPSHOT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Data snapshot';
